### ISSUE TITLE
pushable.push() causing unnecessary reads?

### ISSUE THREAD

**Issue by regular** [pull-stream/pull-pushable#3]
I ran into a problem involving pull-pushable that I find quite hard to debug/understand. I am no sure if this is a bug, but it might well be.
## What I am trying to do

I am consuming a paged REST API (youtube playlist). Each request returns a maximum of 50 items along with an optional `nextPageToken`, if there's more data. I want to create a pull-stream of items that automagically does the minimum amount of api requests required.
## Approach

My idea is to have a `pushable` stream of `pageTokens` that are `pull.asyncMap`ed to a `api` stream, that returns an api response stream created by `hyperquest`. I am then using `pull-tee` to fork off a JSONStream that parses the `nextPage`Token entry and feeds it into a `pull.through` that pushes the new token onto the `pushable`. (This is sort of a feedback loop)

The main sink coming out of `pull-tee` is then fed into yet another JSONStream for parsing the actual items.

``` js
var pull = require('pull-stream');
var toPullStream = require('stream-to-pull-stream');
var pullPush = require('pull-pushable');
var tee = require('pull-tee');
var JSONStream = require('JSONStream');

var pages = pullPush();

// mock for the actual api stream
var api = pull.asyncMap(function(page, cb) {
    console.log('requesting page', page);
    var response;
    if (page.length<10) {
        response = {nextPage: page + ">"};
    } else {
        response = {};
    }
    response.items = [
        {name: 'foo'},
        {name: 'bar'}
    ];
    setTimeout(function() {
        console.log('response');
        cb(null, pull.values(JSON.stringify(response).split('')));
    }, 1000);
});

function iteratePages() {
   return pull(
        toPullStream(JSONStream.parse(['nextPage'])),
        pull.collect(function(err, tokens) {
            if (err) throw err;
            console.log('tokens', tokens);
            process.nextTick(function() {
            if (tokens.length) {
                pages.push(tokens[0]);
            } else {
                pages.end();
            }
            });
        })
    );
}

pull(
    pages,
    pull.prepend('START'),
    api,
    pull.map(function(responseStream) {
        return pull(
            responseStream,
            tee(iteratePages()),
            toPullStream(JSONStream.parse(['items', true, 'name']))
        );
    }),
    pull.take(2),
    pull.log()
);
```
## The Problem

This all works fine, except for the whole construct not being lazy enough!
When I do a pull.take(5), I'd expect only one request to be sent. However the `pushable.push()` causes another `read()` from the `api` stream and thus another http request.
## Simplified case

I simplified the code to:

``` js
var pull = require('pull-stream');
var pullPush = require('pull-pushable');

var pages = pullPush();
pages.push(1);

pull(
    pages,
    pull.through(function() {
        console.log('calling through');
        pages.push(2);
    }),
    pull.take(2),
    pull.log()
);
```

the output is:

```
calling through
1
calling through
2
calling through
calling through
```

As I said, I am not sure whether this is intended behaviour or not and, if not, in which module the problem actually is. I did a lot of poking around and printf debugging but did not end up with a clear picture of why these extra reads are being made.

I would appreciate any comment or hint that shed some light, if you can find the time.

Thanks again for pull-streams, they really feel like streams done right!

**Comment by dominictarr** [comment]
there might be an easier way to do this. pull-pushable is useful sometimes, but you should generally try and avoid using it, especially when you want to make something be lazy.

What i'd do, is use pull.flatten (in pull-streams module). pull.flattern takes a stream of arrays, or a stream of streams, and maps that to a stream of items. So, you could make your request for each token, and read out each item, only consuming the next token when you have read the output from the previous.
But, you could also map to a JSONStream from each response (as you describe) and then flatten that.
Flattening the arrays is probably good enough. since it's paged the responses probably arn't very big. JSONStream is only _really_ useful when the responses are _very large_. but this is your call.

**Comment by regular** [comment]
Thanks for your thoughts! I also have the strong feeling that there must be an easier solution.

I actually played with pull-flatten to flatten the stream of streams and it works fine. Getting from a set of tokens to a stream of items is no problem. What I am struggling with is expanding the set of items when new tokes are being discovered without braking laziness.

That's probably the wrong way to think about it though. Instead of manipulating an external Source, the Through stream should just save the `nextToken` in its own state and use it once its internal buffer of items is exhausted – less moving parts.

**Comment by dominictarr** [comment]
Oh right, well maybe you want something that is like reduce but in reverse: dereduce... or expand.
it takes a state (the initial token) returns a stream/array/value + next state.
next time the expand/dereduce function is called, it's input is the next state from the previous call.

that seems to be the thing here... there is the sequence of states, but also the "side effect" of the data that is comming off the stream?

**Comment by regular** [comment]
Yes, exactly! Interesting thought. Does a generic dereduce/expand thing already exist in the pull-\* universe?

**Comment by regular** [comment]
You mean something like:

``` js
var dereduce = 
function (read, expand, initialState) {
  var state = initialState
  return function (abort, cb) {
    read(abort, function (end, data) {
      try {
       var result = expand(state, data)
       state = result[0] 
       data = !end ? result[1] : null
      } catch (err) {
        return read(err, function () {
          return cb(err)
        })
      }
      cb(end, data)
    })
  }
}
```

?

**Comment by regular** [comment]
Or, maybe, it should be a Source:

Something like:

``` js
var dereduce =
function (initialState, expand, onAbort) {
  var state = initialState
  return function (abort, cb) {
    if(abort)
      return abortCb(cb, abort, onAbort)

    expand(state, function(err, newState, data) {
      state = newState
      cb(err, data)
    })

  }
}
```

Could be used like this

``` js
pull(
  dereduce('START', function(token, cb) {
    pull(
      hyperquest(url(token)),
      pull.collect(function(err, response) {
        var result = JSON.parse(response)
        cb(err || result.nextToken ? null : true, result.nextToken, result.items)
    }),
  }),
  pull.flatten(),
  pull.log()
)
```

**Comment by regular** [comment]
I turned that last idea into [a module](https://www.npmjs.com/package/pull-generate) and then discovered that an unnecessary http request still is sent because of dominictarr/pull-stream#25

But that's only a problem that occurs while testing.

**Comment by dominictarr** [comment]
@regular yeah, that looks good. but i think it might be nicer to make the signature for `expand` be

``` js
function expand (state, function cb (err, data, nextState) { })
```

that way, next state is naturally optional and you could use this as a base to implement various pull sources like count and infinite. I think this will might be better memorywise than creating a new array each time too.

**Comment by regular** [comment]
Right, having the newState last is a nicer signature indeed. (I don't quite get how this prevents new arrays from being created though?)

I am unsure whether `dereduce`/`expand` are still good names for this. I mean, it _could_ be used to expand a series of single values into a stream of arrays or a stream of streams. But, like in the examples you gave with `count` and `infinite` it can also be used to map a certain state to a certain single value. In general, it generates a stream of values by calling a generator function, much like `infinite`. 

How do you feel about `generate` as a name? (I might miss the fact that `expand` is an established name for exactly what we are talking about)

**Comment by dominictarr** [comment]
Generate is a much better name. I was just thinking about how it was the
reverse of reduce.

**Comment by dominictarr** [comment]
I though I saw in you code somewhere you where doing cb(null, [newState,
data]) I could be mistaken or that was in a draft?

**Comment by regular** [comment]
No, I'm just [calling the cb with three parameters instead](https://github.com/regular/pull-generate/blob/master/index.js#L16)
(I don't think we chatted yet :)

**Comment by dominictarr** [comment]
ah, cool
